### ISSUE TITLE
how to scan multiple barcode and retrieve data?

### ISSUE THREAD

**Issue by ghost** [Logomorph/VisionKitBarcodeScanner#1]
I'm trying to scan multiple barcodes one after another and show data to existing list.

**Comment by Logomorph** [comment]
At this point, it's not possible. It should be fairly easy to do, so I'll have a look. The scanner stops the scan session when it reads a barcode, so I need to add some code to turn it back on from the delegate :)
Thanks for the issue!

**Comment by Logomorph** [comment]
@Autonom8Lab I assume you want to keep the scanner open while you scan multiple codes, right?

**Comment by Logomorph** [comment]
@Autonom8Lab I added an extra configuration bool that enables continuous scanning. Let me know if that fixes the issue :)

**Comment by Logomorph** [comment]
The way you do this is by setting
`shouldKeepScanSessionActive  = true`
when initializing the scanner controller and then the delegate function
`barcodeScanner(_ scanner:BarcodeScannerViewController, read code:String)`
will get called every time it reads a barcode. When you're done, you can dismiss the controller and everything will stop.
